spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5432/team_management
    user: postgres
    password:

  datasource:
    name: team-management
    password:
    url: jdbc:postgresql://localhost:5432/team_management
    username: postgres

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true

server:
  port: 8082
